name: elecon
description: エレベータ混雑解消アプリ
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For Firebase
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0

  # For Bluetooth
  flutter_blue: ^0.8.0

  # For Device Info
  device_info: ^2.0.2

  # For Lint
  pedantic: ^1.11.1

  # For UIs
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0

  # For Architecture
  hooks_riverpod: ^0.14.0+4
  flutter_hooks: ^0.17.0

  # For Navigation
  auto_route: ^2.2.0

  # For Model
  freezed_annotation: ^0.14.2
  json_serializable: ^4.1.4

  # For DateTime
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For App
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

  # command: flutter packages pub run build_runner build
  build_runner: ^2.0.6

  # For Assets
  flutter_gen_runner: ^3.1.1

  # For Navigation
  auto_route_generator: ^2.1.0

  # For Model
  freezed: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/image/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/image/icon.png

flutter_native_splash:
  image: assets/image/icon.png
  color: FFFFFF
